print("Hello")
name= input("Enter your name please:")
age = input("Enter your current age:")
location = input("Enter your location:")
print("Hello",name,"you are ",age,'years old and you live in ',location)